//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.22 at 11:34:18 AM CET 
//


package org.louhan.plausex.xjc;


import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlAttribute;


/**
 * <p>Java class for dossierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dossierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="socialBenefitCode" type="{http://bfs.ch/shs/delivery/validation}shsStringRequiredType"/>
 *         &lt;element name="socialBenefitDesc" type="{http://bfs.ch/shs/delivery/validation}shsStringRequiredType"/>
 *         &lt;element name="municipalityId" type="{http://bfs.ch/shs/delivery/validation}HistoryMunicipalityIdType"/>
 *         &lt;element name="residentialStatus" type="{http://bfs.ch/shs/delivery/validation}shsCodeType"/>
 *         &lt;element name="rentFullApartment" type="{http://bfs.ch/shs/delivery/validation}shsBetragType"/>
 *         &lt;element name="rentShare" type="{http://bfs.ch/shs/delivery/validation}shsBetragType"/>
 *         &lt;element name="apartmentSize" type="{http://bfs.ch/shs/delivery/validation}shsCodeType"/>
 *         &lt;element name="hhMembers" type="{http://bfs.ch/shs/delivery/validation}shsCodeType"/>
 *         &lt;element name="closingReason" type="{http://bfs.ch/shs/delivery/validation}shsCodeType"/>
 *         &lt;element name="dossierRespPersonId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dossierRespPersonName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateStartEntitlement" type="{http://bfs.ch/shs/delivery/validation}shsDateType"/>
 *         &lt;element name="addressCorrespondence" type="{http://bfs.ch/shs/delivery/validation}addressCorrespondenceType"/>
 *         &lt;element name="persons" type="{http://bfs.ch/shs/delivery/validation}personsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dossierId" use="required" type="{http://bfs.ch/shs/delivery/validation}shsStringRequiredType" />
 *       &lt;attribute name="dossierProfId" use="required" type="{http://bfs.ch/shs/delivery/validation}shsStringRequiredType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dossierType", propOrder = {
    "serviceId",
    "serviceDescription",
    "socialBenefitCode",
    "socialBenefitDesc",
    "municipalityId",
    "residentialStatus",
    "rentFullApartment",
    "rentShare",
    "apartmentSize",
    "hhMembers",
    "closingReason",
    "dossierRespPersonId",
    "dossierRespPersonName",
    "dateStartEntitlement",
    "addressCorrespondence",
    "persons"
})
public class DossierType {

    @XmlElement(required = true)
    protected String serviceId;
    @XmlElement(required = true)
    protected String serviceDescription;
    @XmlElement(required = true)
    protected String socialBenefitCode;
    @XmlElement(required = true)
    protected String socialBenefitDesc;
    protected int municipalityId;
    @XmlElement(required = true)
    protected String residentialStatus;
    @XmlElement(required = true)
    protected String rentFullApartment;
    @XmlElement(required = true)
    protected String rentShare;
    @XmlElement(required = true)
    protected String apartmentSize;
    @XmlElement(required = true)
    protected String hhMembers;
    @XmlElement(required = true)
    protected String closingReason;
    @XmlElement(required = true)
    protected String dossierRespPersonId;
    @XmlElement(required = true)
    protected String dossierRespPersonName;
    @XmlElement(required = true)
    protected String dateStartEntitlement;
    @XmlElement(required = true)
    protected AddressCorrespondenceType addressCorrespondence;
    @XmlElement(required = true)
    protected PersonsType persons;
    @XmlAttribute(name = "dossierId", required = true)
    protected String dossierId;
    @XmlAttribute(name = "dossierProfId", required = true)
    protected String dossierProfId;

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceId(String value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the serviceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDescription() {
        return serviceDescription;
    }

    /**
     * Sets the value of the serviceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDescription(String value) {
        this.serviceDescription = value;
    }

    /**
     * Gets the value of the socialBenefitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocialBenefitCode() {
        return socialBenefitCode;
    }

    /**
     * Sets the value of the socialBenefitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocialBenefitCode(String value) {
        this.socialBenefitCode = value;
    }

    /**
     * Gets the value of the socialBenefitDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocialBenefitDesc() {
        return socialBenefitDesc;
    }

    /**
     * Sets the value of the socialBenefitDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocialBenefitDesc(String value) {
        this.socialBenefitDesc = value;
    }

    /**
     * Gets the value of the municipalityId property.
     * 
     */
    public int getMunicipalityId() {
        return municipalityId;
    }

    /**
     * Sets the value of the municipalityId property.
     * 
     */
    public void setMunicipalityId(int value) {
        this.municipalityId = value;
    }

    /**
     * Gets the value of the residentialStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidentialStatus() {
        return residentialStatus;
    }

    /**
     * Sets the value of the residentialStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidentialStatus(String value) {
        this.residentialStatus = value;
    }

    /**
     * Gets the value of the rentFullApartment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRentFullApartment() {
        return rentFullApartment;
    }

    /**
     * Sets the value of the rentFullApartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRentFullApartment(String value) {
        this.rentFullApartment = value;
    }

    /**
     * Gets the value of the rentShare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRentShare() {
        return rentShare;
    }

    /**
     * Sets the value of the rentShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRentShare(String value) {
        this.rentShare = value;
    }

    /**
     * Gets the value of the apartmentSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApartmentSize() {
        return apartmentSize;
    }

    /**
     * Sets the value of the apartmentSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApartmentSize(String value) {
        this.apartmentSize = value;
    }

    /**
     * Gets the value of the hhMembers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHhMembers() {
        return hhMembers;
    }

    /**
     * Sets the value of the hhMembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHhMembers(String value) {
        this.hhMembers = value;
    }

    /**
     * Gets the value of the closingReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosingReason() {
        return closingReason;
    }

    /**
     * Sets the value of the closingReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosingReason(String value) {
        this.closingReason = value;
    }

    /**
     * Gets the value of the dossierRespPersonId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDossierRespPersonId() {
        return dossierRespPersonId;
    }

    /**
     * Sets the value of the dossierRespPersonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDossierRespPersonId(String value) {
        this.dossierRespPersonId = value;
    }

    /**
     * Gets the value of the dossierRespPersonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDossierRespPersonName() {
        return dossierRespPersonName;
    }

    /**
     * Sets the value of the dossierRespPersonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDossierRespPersonName(String value) {
        this.dossierRespPersonName = value;
    }

    /**
     * Gets the value of the dateStartEntitlement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateStartEntitlement() {
        return dateStartEntitlement;
    }

    /**
     * Sets the value of the dateStartEntitlement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateStartEntitlement(String value) {
        this.dateStartEntitlement = value;
    }

    /**
     * Gets the value of the addressCorrespondence property.
     * 
     * @return
     *     possible object is
     *     {@link AddressCorrespondenceType }
     *     
     */
    public AddressCorrespondenceType getAddressCorrespondence() {
        return addressCorrespondence;
    }

    /**
     * Sets the value of the addressCorrespondence property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressCorrespondenceType }
     *     
     */
    public void setAddressCorrespondence(AddressCorrespondenceType value) {
        this.addressCorrespondence = value;
    }

    /**
     * Gets the value of the persons property.
     * 
     * @return
     *     possible object is
     *     {@link PersonsType }
     *     
     */
    public PersonsType getPersons() {
        return persons;
    }

    /**
     * Sets the value of the persons property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonsType }
     *     
     */
    public void setPersons(PersonsType value) {
        this.persons = value;
    }

    /**
     * Gets the value of the dossierId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDossierId() {
        return dossierId;
    }

    /**
     * Sets the value of the dossierId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDossierId(String value) {
        this.dossierId = value;
    }

    /**
     * Gets the value of the dossierProfId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDossierProfId() {
        return dossierProfId;
    }

    /**
     * Sets the value of the dossierProfId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDossierProfId(String value) {
        this.dossierProfId = value;
    }

}
