//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.22 at 11:05:51 PM CET 
//


package org.louhan.plausex.xjc;


import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.bfs.shs.delivery.validation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.bfs.shs.delivery.validation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InfosType }
     * 
     */
    public InfosType createInfosType() {
        return new InfosType();
    }

    /**
     * Create an instance of {@link Delivery }
     * 
     */
    public Delivery createDelivery() {
        return new Delivery();
    }

    /**
     * Create an instance of {@link DossiersType }
     * 
     */
    public DossiersType createDossiersType() {
        return new DossiersType();
    }

    /**
     * Create an instance of {@link AccountingEntriesType }
     * 
     */
    public AccountingEntriesType createAccountingEntriesType() {
        return new AccountingEntriesType();
    }

    /**
     * Create an instance of {@link DossierType }
     * 
     */
    public DossierType createDossierType() {
        return new DossierType();
    }

    /**
     * Create an instance of {@link PersonsType }
     * 
     */
    public PersonsType createPersonsType() {
        return new PersonsType();
    }

    /**
     * Create an instance of {@link AddressCorrespondenceType }
     * 
     */
    public AddressCorrespondenceType createAddressCorrespondenceType() {
        return new AddressCorrespondenceType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link AccountingEntryType }
     * 
     */
    public AccountingEntryType createAccountingEntryType() {
        return new AccountingEntryType();
    }

    /**
     * Create an instance of {@link InfosType.FfsInfos }
     * 
     */
    public InfosType.FfsInfos createInfosTypeFfsInfos() {
        return new InfosType.FfsInfos();
    }

    /**
     * Create an instance of {@link InfosType.ExpInfos }
     * 
     */
    public InfosType.ExpInfos createInfosTypeExpInfos() {
        return new InfosType.ExpInfos();
    }

}
