//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.22 at 11:05:51 PM CET 
//


package org.louhan.plausex.xjc;


import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for shsMaritalStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="shsMaritalStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="1"/>
 *     &lt;enumeration value="2"/>
 *     &lt;enumeration value="3"/>
 *     &lt;enumeration value="4"/>
 *     &lt;enumeration value="5"/>
 *     &lt;enumeration value="6"/>
 *     &lt;enumeration value="7"/>
 *     &lt;enumeration value="9"/>
 *     &lt;enumeration value=""/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "shsMaritalStatusType")
@XmlEnum
public enum ShsMaritalStatusType {

    @XmlEnumValue("1")
    SINGLE("1"),
    @XmlEnumValue("2")
    MARRIED("2"),
    @XmlEnumValue("3")
    SEPARATED("3"),
    @XmlEnumValue("4")
    DIVORCED("4"),
    @XmlEnumValue("5")
    WIDOWED("5"),
    @XmlEnumValue("6")
    REGISTERED_PARTNERSHIP("6"),
    @XmlEnumValue("7")
    DISSOLVED_PARTNERSHIP("7"),
    @XmlEnumValue("9")
    UNKNOWN("9"),
    @XmlEnumValue("")
    EMPTY("");
    private final String value;

    ShsMaritalStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShsMaritalStatusType fromValue(String v) {
        for (ShsMaritalStatusType c: ShsMaritalStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
