//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.22 at 11:05:51 PM CET 
//


package org.louhan.plausex.xjc;


import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for shsSeparationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="shsSeparationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="1"/>
 *     &lt;enumeration value="2"/>
 *     &lt;enumeration value=""/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "shsSeparationType")
@XmlEnum
public enum ShsSeparationType {

    @XmlEnumValue("1")
    YES("1"),
    @XmlEnumValue("2")
    NO("2"),
    @XmlEnumValue("")
    EMPTY("");
    private final String value;

    ShsSeparationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShsSeparationType fromValue(String v) {
        for (ShsSeparationType c: ShsSeparationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
