//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.22 at 11:05:51 PM CET 
//


package org.louhan.plausex.xjc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>Java class for shsSexType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="shsSexType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="1"/>
 *     &lt;enumeration value="2"/>
 *     &lt;enumeration value="3"/>
 *     &lt;enumeration value=""/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "shsSexType")
@XmlEnum
public enum ShsSexType {

    @XmlEnumValue("1")
    MALE("1"),
    @XmlEnumValue("2")
    FEMALE("2"),
    @XmlEnumValue("3")
    OTHER("3"),
    @XmlEnumValue("")
    EMPTY("");
    private final String value;

    ShsSexType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShsSexType fromValue(String v) {
        for (ShsSexType c: ShsSexType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
