//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.22 at 11:34:18 AM CET 
//


package org.louhan.xjc;


import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="infos" type="{http://bfs.ch/shs/delivery/validation}infosType"/>
 *         &lt;element name="dossiers" type="{http://bfs.ch/shs/delivery/validation}dossiersType"/>
 *         &lt;element name="accountingEntries" type="{http://bfs.ch/shs/delivery/validation}accountingEntriesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "infos",
    "dossiers",
    "accountingEntries"
})
@XmlRootElement(name = "delivery")
public class Delivery {

    @XmlElement(required = true)
    protected InfosType infos;
    @XmlElement(required = true)
    protected DossiersType dossiers;
    @XmlElement(required = true)
    protected AccountingEntriesType accountingEntries;

    /**
     * Gets the value of the infos property.
     * 
     * @return
     *     possible object is
     *     {@link InfosType }
     *     
     */
    public InfosType getInfos() {
        return infos;
    }

    /**
     * Sets the value of the infos property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfosType }
     *     
     */
    public void setInfos(InfosType value) {
        this.infos = value;
    }

    /**
     * Gets the value of the dossiers property.
     * 
     * @return
     *     possible object is
     *     {@link DossiersType }
     *     
     */
    public DossiersType getDossiers() {
        return dossiers;
    }

    /**
     * Sets the value of the dossiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link DossiersType }
     *     
     */
    public void setDossiers(DossiersType value) {
        this.dossiers = value;
    }

    /**
     * Gets the value of the accountingEntries property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingEntriesType }
     *     
     */
    public AccountingEntriesType getAccountingEntries() {
        return accountingEntries;
    }

    /**
     * Sets the value of the accountingEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingEntriesType }
     *     
     */
    public void setAccountingEntries(AccountingEntriesType value) {
        this.accountingEntries = value;
    }

}
