//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.22 at 11:34:18 AM CET 
//


package org.louhan.xjc;



import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlAttribute;



/**
 * <p>Java class for personType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="personType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vn" type="{http://bfs.ch/shs/delivery/validation}shsVnType"/>
 *         &lt;element name="officialName" type="{http://bfs.ch/shs/delivery/validation}baseNameType"/>
 *         &lt;element name="firstName" type="{http://bfs.ch/shs/delivery/validation}baseNameType"/>
 *         &lt;element name="dateOfBirth" type="{http://bfs.ch/shs/delivery/validation}shsDateType"/>
 *         &lt;element name="sex" type="{http://bfs.ch/shs/delivery/validation}shsSexType"/>
 *         &lt;element name="maritalStatus" type="{http://bfs.ch/shs/delivery/validation}shsMaritalStatusType"/>
 *         &lt;element name="separation" type="{http://bfs.ch/shs/delivery/validation}shsSeparationType"/>
 *         &lt;element name="countryId" type="{http://bfs.ch/shs/delivery/validation}shsCountryIdType"/>
 *         &lt;element name="education" type="{http://bfs.ch/shs/delivery/validation}shsCodeType"/>
 *         &lt;element name="educationLevel" type="{http://bfs.ch/shs/delivery/validation}shsCodeType"/>
 *         &lt;element name="employmentSituation" type="{http://bfs.ch/shs/delivery/validation}shsCodeType"/>
 *         &lt;element name="employmentRate" type="{http://bfs.ch/shs/delivery/validation}shsCodeType"/>
 *         &lt;element name="relationshipToApplicant" type="{http://bfs.ch/shs/delivery/validation}shsCodeType"/>
 *         &lt;element name="foreignerCategoryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="foreignerCategoryDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datEntry" type="{http://bfs.ch/shs/delivery/validation}shsDateType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="personId" use="required" type="{http://bfs.ch/shs/delivery/validation}shsStringRequiredType" />
 *       &lt;attribute name="PersonProfId" use="required" type="{http://bfs.ch/shs/delivery/validation}shsStringRequiredType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "personType", propOrder = {
    "vn",
    "officialName",
    "firstName",
    "dateOfBirth",
    "sex",
    "maritalStatus",
    "separation",
    "countryId",
    "education",
    "educationLevel",
    "employmentSituation",
    "employmentRate",
    "relationshipToApplicant",
    "foreignerCategoryId",
    "foreignerCategoryDesc",
    "datEntry"
})
public class PersonType {

    @XmlElement(required = true, nillable = true)
    protected String vn;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String officialName;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String firstName;
    @XmlElement(required = true)
    protected String dateOfBirth;
    @XmlElement(required = true)
    protected String sex;
    @XmlElement(required = true)
    protected String maritalStatus;
    @XmlElement(required = true)
    protected String separation;
    @XmlElement(required = true)
    protected String countryId;
    @XmlElement(required = true)
    protected String education;
    @XmlElement(required = true)
    protected String educationLevel;
    @XmlElement(required = true)
    protected String employmentSituation;
    @XmlElement(required = true)
    protected String employmentRate;
    @XmlElement(required = true)
    protected String relationshipToApplicant;
    @XmlElement(required = true)
    protected String foreignerCategoryId;
    @XmlElement(required = true)
    protected String foreignerCategoryDesc;
    @XmlElement(required = true)
    protected String datEntry;
    @XmlAttribute(name = "personId", required = true)
    protected String personId;
    @XmlAttribute(name = "PersonProfId", required = true)
    protected String personProfId;

    /**
     * Gets the value of the vn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVn() {
        return vn;
    }

    /**
     * Sets the value of the vn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVn(String value) {
        this.vn = value;
    }

    /**
     * Gets the value of the officialName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficialName() {
        return officialName;
    }

    /**
     * Sets the value of the officialName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficialName(String value) {
        this.officialName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSex(String value) {
        this.sex = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the separation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeparation() {
        return separation;
    }

    /**
     * Sets the value of the separation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparation(String value) {
        this.separation = value;
    }

    /**
     * Gets the value of the countryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryId() {
        return countryId;
    }

    /**
     * Sets the value of the countryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryId(String value) {
        this.countryId = value;
    }

    /**
     * Gets the value of the education property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducation() {
        return education;
    }

    /**
     * Sets the value of the education property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducation(String value) {
        this.education = value;
    }

    /**
     * Gets the value of the educationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducationLevel() {
        return educationLevel;
    }

    /**
     * Sets the value of the educationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducationLevel(String value) {
        this.educationLevel = value;
    }

    /**
     * Gets the value of the employmentSituation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentSituation() {
        return employmentSituation;
    }

    /**
     * Sets the value of the employmentSituation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentSituation(String value) {
        this.employmentSituation = value;
    }

    /**
     * Gets the value of the employmentRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentRate() {
        return employmentRate;
    }

    /**
     * Sets the value of the employmentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentRate(String value) {
        this.employmentRate = value;
    }

    /**
     * Gets the value of the relationshipToApplicant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipToApplicant() {
        return relationshipToApplicant;
    }

    /**
     * Sets the value of the relationshipToApplicant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipToApplicant(String value) {
        this.relationshipToApplicant = value;
    }

    /**
     * Gets the value of the foreignerCategoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignerCategoryId() {
        return foreignerCategoryId;
    }

    /**
     * Sets the value of the foreignerCategoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignerCategoryId(String value) {
        this.foreignerCategoryId = value;
    }

    /**
     * Gets the value of the foreignerCategoryDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignerCategoryDesc() {
        return foreignerCategoryDesc;
    }

    /**
     * Sets the value of the foreignerCategoryDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignerCategoryDesc(String value) {
        this.foreignerCategoryDesc = value;
    }

    /**
     * Gets the value of the datEntry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatEntry() {
        return datEntry;
    }

    /**
     * Sets the value of the datEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatEntry(String value) {
        this.datEntry = value;
    }

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonId(String value) {
        this.personId = value;
    }

    /**
     * Gets the value of the personProfId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonProfId() {
        return personProfId;
    }

    /**
     * Sets the value of the personProfId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonProfId(String value) {
        this.personProfId = value;
    }

}
